Traceback (most recent call last):
  File "./upload.py", line 164, in <module>
    mouse.process_mouse_data()
  File "/data/informatics/morphology_clustering/swanky/bin/mouse.py", line 477, in process_mouse_data
    fetch_autotrace(filename, spec_id)
  File "/data/informatics/morphology_clustering/swanky/bin/mouse.py", line 57, in fetch_autotrace
    if len(result[0]) > 0:
IndexError: list index out of range
